### ISSUE TITLE
请教个多进程消费的问题

### ISSUE THREAD

**Issue by zhb127** [Quinton/egg-kafkajs#3]
egg 默认启动 cpu 核心数量的 app worker 进程，在这个插件 app.js 里面看到了注册消费者的代码，那这样是只启动四个进程来消费队列，如果想要按照不同主题，启动不同数量的消费者进程。应该怎么做呢

**Comment by tsui66** [comment]
@zhb127 首先你得分析你这样做的场景是什么、出发点又是什么； 其次 worker 进程数默认是 CPU 核数或者 `egg-scripts --worker <number>`。这是从非业务代码层次上控制的。

**Comment by zhb127** [comment]
嗯嗯，@Quinton 感谢回复，我在这里补充一下我的场景、出发点。

### 场景

在开发支付模块时（对接第三方支付网关），将支付请求提交给第三方支付网关，同时，应用提供一个 webhook url 接收第三方支付网关的支付结果通知，其中，在 webhook 里直接将通知写入到消息队列，由应用在后台开启多个进程消费该消息队列。

### 出发点

由于，一开始看到 egg 很多消息队列的插件，是在 app.js 中直接注册消费者代码，于是，尝试在消费者代码中，并添加了一些耗时的操作（例如：sleep 模块会阻塞线程的操作），测试发现会影响 egg 应用的 http 服务响应。于是，后面采用多应用方式隔离不同的服务：web_api、job_queue。后来，在实现 job_queue 应用，又希望，能针对不同的 topic 消息队列，开启不同数量的进程来消费，故有此问题。

**Comment by tsui66** [comment]
@zhb127 了解了，你们的做法是微服务；想在应用里配置消息队列暂时没有哦

**Comment by zhb127** [comment]
@Quinton  嗯嗯，好的。那我自己考虑看看，单独在 job_queue 应用中，怎么更好地处理队列消费的问题。😁
